apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial-monitor
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
  - port: trialport
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default