{
 "title": "ND064 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Uptime",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time( kube_pod_container_status_running{container=~\"frontend\"}[$__range]))*30/$__range_s",
       "legendFormat": "Frontend"
      },
      {
       "expr": "sum(sum_over_time( kube_pod_container_status_running{container=~\"backend\"}[$__range]))*30/$__range_s",
       "legendFormat": "Backend"
      }
     ]
    },
    {
     "title": "Availability (at least 1 pod ready)",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{container=\"backend\"}==1)",
       "legendFormat": "Backend"
      },
      {
       "expr": "sum(kube_pod_container_status_ready{container=\"frontend\"}==1)",
       "legendFormat": "Frontend"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ErrorRate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(flask_http_request_total{status=~\"(4|5)..\", container=~\"backend\"}[$__range]))\n/\nsum(increase(flask_http_request_total{container=~\"backend\"}[$__range]))*100",
       "legendFormat": "Backend"
      },
      {
       "expr": "sum(increase(flask_http_request_total{status=~\"(4|5)..\", container=~\"frontend\"}[$__range]))\n/\nsum(increase(flask_http_request_total{container=~\"frontend\"}[$__range]))*100",
       "legendFormat": "Frontend"
      }
     ]
    },
    {
     "title": "HTTP 2xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=~\"2..\", container=~\"backend\"}[1m]\n))",
       "legendFormat": "Backend"
      },
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=~\"2..\", container=~\"frontend\"}[1m]\n))",
       "legendFormat": "Frontend"
      }
     ]
    },
    {
     "title": "HTTP 4xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=~\"4.*\", container=~\"backend\"}[1m]\n))",
       "legendFormat": "Backend"
      },
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=~\"4.*\", container=~\"frontend\"}[1m]\n))",
       "legendFormat": "Frontend"
      }
     ]
    },
    {
     "title": "HTTP 5xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=\"500\", container=~\"backend\"}[1m]\n))",
       "legendFormat": "Backend"
      },
      {
       "expr": "sum(increase(\n  flask_http_request_total{status=\"500\", container=~\"frontend\"}[1m]\n))",
       "legendFormat": "Frontend"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(\n  flask_http_request_duration_seconds_sum{status=\"200\"}[$__range]\n))\n /\nsum(rate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[$__range]\n))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request durations <300ms",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(sum(increase(\n  flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[$__range]\n))\n / ignoring (le)\nsum(increase(\n  flask_http_request_duration_seconds_count{status=\"200\"}[$__range]\n)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Jaeger Backend API Traces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      { "operation": "api", "service": "backend-tracer" }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU & Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Load"
      },
      {
       "expr": "(node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Load"
      }
     ]
    },
    {
     "title": "Max CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Load"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100",
       "legendFormat": "Memory Load"
      }
     ]
    },
    {
     "title": "Max Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100",
       "legendFormat": "Memory Load"
      }
     ]
    }
   ]
  }
 ]
}